services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/backend
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      RAILS_ENV: production
    networks:
      - my-network
  database:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresqldb/data
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - my-network
networks:
  my-network:
volumes:
  gem_cache:
  db_data:
